package com.darksvoicesai

import android.content.ClipData
import android.content.Context
import android.content.Intent
import android.media.MediaPlayer
import android.net.Uri
import android.os.Bundle
import android.provider.Settings
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.horizontalScroll
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import androidx.lifecycle.viewmodel.compose.viewModel
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import java.io.File
import java.net.HttpURLConnection
import java.net.URL
import java.text.SimpleDateFormat
import java.util.*
import android.util.Base64

private val Bg = Color(0xFF020617); private val Card = Color(0xFF0F172A); private val Emerald = Color(0xFF10B981); private val Slate = Color(0xFF94A3B8); private val Rose = Color(0xFFF43F5E)

data class Voice(val id:String,val bn:String,val hi:String,val titleBn:String,val titleHi:String,val descBn:String,val descHi:String,val badgeBn:String,val badgeHi:String,val gender:String)
data class Tone(val id:String,val bn:String,val hi:String,val descBn:String,val descHi:String)
data class Msg(val id:String,val text:String,val spoken:String,val audioUrl:String?,val wavUrl:String?,val mp3Url:String?,val duration:Double,val voice:String,val gender:String,val language:String,val tone:String,val timestamp:Long,val sampleRate:Int,val format:String,val wavSize:Long?,val mp3Size:Long?)

private val males=listOf(
 Voice("Charon","শ্যারন","शैरन","গম্ভীর ও আত্মবিশ্বাসী পুরুষ কণ্ঠ","गंभीर और प्रभावशाली पुरुष आवाज","গম্ভীর, স্পষ্ট ও গভীর কণ্ঠ। প্রাতিষ্ঠানিক বার্তা, ঘোষণা ও ভাবগম্ভীর আলোচনার জন্য সেরা।","गंभीर, स्पष्ट और आधिकारिक स्वर।","সবচেয়ে জনপ্রিয়","सर्वाधिक लोकप्रिय","male"),
 Voice("Fenrir","ফেনরির","फेनरिर","উষ্ণ ও স্পষ্ট পুরুষ কণ্ঠ","स्पष्ट और आत्मीय पुरुष आवाज","স্পষ্ট শব্দ উচ্চারণ ও আন্তরিক ভাব। ব্যক্তিগত বার্তা, দিকনির্দেশনা ও বন্ধুসুলভ কথোপকথনের জন্য উপযোগী।","सटीक और मधुर उच्चारण।","উচ্চ স্পষ্টতা","उच्च स्पष्टता","male"),
 Voice("Puck","পাক","पक","প্রাণবন্ত ও চনমনে পুরুষ কণ্ঠ","उत्साही और युवा पुरुष आवाज","গতিশীল ও প্রাণোচ্ছ্বল সুর। দ্রুত আপডেট, শুভেচ্ছা ও বন্ধুদের মাঝে মেসেজ পাঠানোর জন্য উপযুক্ত।","ऊर्जावान और सहज प्रवाह।","প্রাণবন্ত","ऊर्जावान","male"))
private val females=listOf(
 Voice("Kore","কোরে","कोरे","মিষ্টি, সুরেলা ও শান্ত নারী কণ্ঠ","मधुर, शांत और स्वाभाविक महिला आवाज","কোমল, শান্ত এবং অত্যন্ত মিষ্টি বাচনভঙ্গি। শুভেচ্ছা, ব্যক্তিগত বার্তা ও ভাবঘন কথার জন্য অত্যন্ত চমৎকার।","अत्यंत सौम्य, मधुर और प्राकृतिक स्वर।","সেরা পছন্দ","सर्वश्रेष्ठ पसंद","female"),
 Voice("Zephyr","জেফির","ज़ेफ़िर","উজ্জ্বল, স্পষ্ট ও আধুনিক নারী কণ্ঠ","स्पष्ट, आधुनिक और सजीव महिला आवाज","উজ্জ্বল ও পরিষ্কার উচ্চারণ। অডিও গাইড, সোশ্যাল মিডিয়া বার্তা ও ব্যাখ্যার জন্য আদর্শ।","स्पष्ट और आत्मविश्वास से भरा आधुनिक स्वर।","স্ফটিক স্পষ্ট","सटीक उच्चारण","female"),
 Voice("Aoede","আওয়েড","आयोड","মার্জিত ও প্রাতিষ্ঠানিক নারী কণ্ঠ","शालीन, औपचारिक और सशक्त महिला आवाज","মার্জিত, পরিশীলিত ও গাম্ভীর্যপূর্ণ বাচনভঙ্গি। অফিসিয়াল আপডেট, ব্যবসায়িক যোগাযোগ ও প্রাতিষ্ঠানিক বার্তার জন্য সেরা।","गंभीर, गरिमामय और पेशेवर अभिव्यक्ति।","প্রাতিষ্ঠানিক","पेशेवर","female"))
private val tones=listOf(
 Tone("natural","স্বাভাবিক কথোপকথন","स्वाभाविक बातचीत","সাধারণ ও স্বাভাবিক বাচনভঙ্গি","सहज और संतुलित दैनिक बोलने का ढंग"),
 Tone("warm","উষ্ণ ও আন্তরিক","आत्मीय और स्नेहपूर्ण","স্নেহশীল ও আন্তরিক অনুভূতির সুর","हृदयस्पर्शी, करुणामय और कोमल प्रवाह"),
 Tone("professional","মার্জিত ও প্রাতিষ্ঠানিক","औपचारिक / पेशेवर","অফিসিয়াল ও গাম্ভীর্যপূর্ণ কণ্ঠ","गंभीर, सुव्यवस्थित और आधिकारिक शैली"),
 Tone("energetic","প্রাণবন্ত ও উদ্দীপক","उत्साही और ऊर्जावान","উচ্ছ্বসিত ও ইতিবাচক মনোভাব","उत्साहपूर्ण, जीवंत और प्रेरक अभिव्यक्ति"))
private val bnPresets=listOf("বন্ধুকে বার্তা" to "আরে ভাই, কেমন আছিস? অনেকদিন পর তোকে নক করলাম। আজ সন্ধ্যায় কি একটু সময় হবে? চায়ের দোকানে কিছুক্ষণ আড্ডা দেওয়া যেত!","কাজের আপডেট" to "শুভ অপরাহ্ন। আমাদের আজকের প্রজেক্টের কাজ সফলভাবে শেষ হয়েছে। ফাইলগুলো আপনার ইমেইলে পাঠিয়ে দেওয়া হলো, দয়া করে একবার দেখে নেবেন।","আন্তরিক শুভেচ্ছা" to "আপনার ও আপনার পরিবারের সকলের প্রতি রইল আন্তরিক ভালোবাসা ও শুভেচ্ছা। আগামী দিনগুলো আপনার জীবনে সুখ, শান্তি ও সমৃদ্ধি বয়ে আনুক।","বাংলিশ টেস্ট" to "ami tomake ekta dorkari kotha bolte chai, free hole amake ekbar call dio please.")
private val hiPresets=listOf("दोस्त को ऑडियो" to "अरे भाई, कैसा है तू? बहुत दिनों बाद तुझे याद किया। आज शाम को थोड़ा समय मिलेगा क्या? चाय की दुकान पर बैठकर गपशप करते हैं!","ऑफिस अपडेट" to "नमस्ते। आज का प्रोजेक्ट कार्य सफलतापूर्वक पूरा हो चुका है। सभी जरूरी फाइलें आपकी ईमेल पर भेज दी गई हैं, कृपया एक बार जांच लें।","हार्दिक शुभकामनाएं" to "आपको और आपके पूरे परिवार को हमारी तरफ से ढेर सारा प्यार और हार्दिक शुभकामनाएं। आने वाला समय आपके जीवन में अपार खुशियां और समृद्धि लाए।","हिंग्लिश टेस्ट" to "namaste bhai, kaisa hai? mujhe aapse ek zaroori baat karni thi, free hote hi mujhe call karna please.")

private const val PREF="darks_voices_history_v2"
private const val DEFAULT_BN="নমস্কার! আমি আপনাকে বাংলায় টেক্সট দিচ্ছি, আপনি এটিকে চমৎকার স্পষ্ট উচ্চারণে একটি প্রাকৃতিক কণ্ঠে ভয়েস মেসেজ করে দিন।"
private const val DEFAULT_HI="नमस्ते! मैं आपको यह संदेश दे रहा हूँ, कृपया इसे बहुत ही स्वाभाविक उच्चारण और स्पष्ट आवाज़ में रिकॉर्ड करें।"

class MainViewModel(private val ctx: Context): ViewModel(){
 var bangla by mutableStateOf(true); var lang by mutableStateOf("bn"); var gender by mutableStateOf("male"); var voice by mutableStateOf("Charon"); var tone by mutableStateOf("natural"); var auto by mutableStateOf(true); var text by mutableStateOf(DEFAULT_BN)
 var busy by mutableStateOf(false); var optimizing by mutableStateOf(false); var error by mutableStateOf<String?>(null); var current by mutableStateOf<Msg?>(null); var history by mutableStateOf(load())
 private fun load():List<Msg>{return try{val a=JSONArray(ctx.getSharedPreferences("app",0).getString(PREF,"[]"));(0 until a.length()).map{parse(a.getJSONObject(it))}}catch(_:Exception){emptyList()}}
 private fun save(){ctx.getSharedPreferences("app",0).edit().putString(PREF,JSONArray().apply{history.forEach{put(toJson(it))}}.toString()).apply()}
 fun delete(id:String){history=history.filterNot{it.id==id};if(current?.id==id)current=null;save()}; fun clear(){history=emptyList();current=null;save()}
 fun langChange(l:String){lang=l;if(text==DEFAULT_BN&&l=="hi")text=DEFAULT_HI else if(text==DEFAULT_HI&&l=="bn")text=DEFAULT_BN}
 fun selectVoice(v:String){voice=v;gender=(males+females).first{it.id==v}.gender}; fun selectGender(g:String){gender=g; if(g=="female"&&!females.any{it.id==voice})voice="Kore"; if(g=="male"&&!males.any{it.id==voice})voice="Charon"}
 fun optimize(){if(text.isBlank()||optimizing)return; optimizing=true;error=null;viewModelScope.launch{try{val j=JSONObject().put("text",text).put("language",lang);val r=Api.post("/api/optimize-text",j.toString());val o=JSONObject(r).optString("optimizedText",text); text=o}catch(e:Exception){error=if(bangla)"উচ্চারণ অপ্টিমাইজেশনে সমস্যা হয়েছে। সরাসরি ভয়েস মেসেজ তৈরি করতে পারেন।" else "Optimization service busy. You can still generate the voice message directly."}finally{optimizing=false}}}
 fun generate(){if(text.isBlank()||busy)return;busy=true;error=null;viewModelScope.launch{try{val j=JSONObject().put("text",text.trim()).put("voice",voice).put("gender",gender).put("language",lang).put("tone",tone).put("autoOptimize",auto);val r=JSONObject(Api.post("/api/tts",j.toString()));if(!r.optBoolean("success",false))throw Exception(r.optString("error","Failed to generate speech"));val id="msg-${System.currentTimeMillis()}"; val wav=saveDataUrl(r.optString("wavUrl",r.optString("audioUrl","")),"${id}.wav"); val mp3=if(r.optString("mp3Url","").isNotBlank())saveDataUrl(r.optString("mp3Url"),"${id}.mp3") else null; val m=Msg(id,text.trim(),r.optString("spokenText",text.trim()),wav,wav,mp3,r.optDouble("duration",0.0),r.optString("voice",voice),r.optString("gender",gender),r.optString("language",lang),tone,System.currentTimeMillis(),r.optInt("sampleRate",24000),r.optString("format","wav"),if(r.has("wavSizeBytes"))r.optLong("wavSizeBytes") else null,if(r.has("mp3SizeBytes"))r.optLong("mp3SizeBytes") else null);current=m;history=listOf(m)+history.take(19);save()}catch(e:Exception){error=e.message?:"Failed to generate voice message. Please try again."}finally{busy=false}}}
 private fun saveDataUrl(data:String,name:String):String{val b64=data.substringAfter(",",data);val bytes=Base64.decode(b64,Base64.DEFAULT);val f=File(ctx.filesDir,name);f.writeBytes(bytes);return f.absolutePath}
 private fun toJson(m:Msg)=JSONObject().apply{put("id",m.id);put("text",m.text);put("spoken",m.spoken);put("audioUrl",m.audioUrl);put("wavUrl",m.wavUrl);put("mp3Url",m.mp3Url);put("duration",m.duration);put("voice",m.voice);put("gender",m.gender);put("language",m.language);put("tone",m.tone);put("timestamp",m.timestamp);put("sampleRate",m.sampleRate);put("format",m.format);put("wavSize",m.wavSize);put("mp3Size",m.mp3Size)}
 private fun parse(o:JSONObject)=Msg(o.optString("id"),o.optString("text"),o.optString("spoken"),o.optString("audioUrl",null),o.optString("wavUrl",null),o.optString("mp3Url",null),o.optDouble("duration",0.0),o.optString("voice","Charon"),o.optString("gender","male"),o.optString("language","bn"),o.optString("tone","natural"),o.optLong("timestamp"),o.optInt("sampleRate",24000),o.optString("format","wav"),if(o.has("wavSize")&&!o.isNull("wavSize"))o.optLong("wavSize") else null,if(o.has("mp3Size")&&!o.isNull("mp3Size"))o.optLong("mp3Size") else null)
}
class MainActivity:ComponentActivity(){override fun onCreate(b:Bundle?){super.onCreate(b);setContent{val vm:MainViewModel= viewModel(factory=object:androidx.lifecycle.ViewModelProvider.Factory{override fun <T:ViewModel> create(c:Class<T>)=MainViewModel(applicationContext) as T});DarksTheme{App(vm)}}}}

object Api{fun post(path:String,body:String):String{val base=BuildConfig.API_BASE_URL.trimEnd('/');if(base.isBlank())throw Exception("Backend URL is not configured. Set API_BASE_URL in app/build.gradle.kts.");val c=(URL(base+path).openConnection() as HttpURLConnection);c.requestMethod="POST";c.connectTimeout=20000;c.readTimeout=120000;c.doOutput=true;c.setRequestProperty("Content-Type","application/json");c.outputStream.use{it.write(body.toByteArray())};val s=if(c.responseCode in 200..299)c.inputStream else c.errorStream;val out=s.bufferedReader().readText();if(c.responseCode !in 200..299)throw Exception(JSONObject(out).optString("error","HTTP ${c.responseCode}"));return out}}

@Composable fun DarksTheme(content:@Composable()->Unit){MaterialTheme(colorScheme=darkColorScheme(background=Bg,surface=Card,primary=Emerald,error=Rose),content=content)}
@Composable fun App(vm:MainViewModel){var icon by remember{mutableStateOf(false)};var showSpoken by remember{mutableStateOf(false)};LazyColumn(modifier=Modifier.fillMaxSize().background(Bg).padding(16.dp),verticalArrangement=Arrangement.spacedBy(16.dp)){item{Header(vm){icon=true}};item{Banner(vm)};item{Editor(vm)};item{VoiceSettings(vm)};vm.error?.let{e->item{ErrorCard(e){vm.error=null}}};item{Button({vm.generate()},enabled=vm.text.isNotBlank()&&!vm.busy,modifier=Modifier.fillMaxWidth().height(52.dp)){Text(if(vm.busy)if(vm.bangla)"ভয়েস তৈরি হচ্ছে..." else "Generating voice..." else if(vm.bangla)"🎙️ ভয়েস মেসেজ তৈরি করুন" else "🎙️ Generate Voice Message",fontWeight=FontWeight.Bold)}};vm.current?.let{m->item{Player(m,vm.bangla,showSpoken){showSpoken=true}}};if(vm.history.isNotEmpty()){item{Text(if(vm.bangla)"পূর্বের ভয়েস মেসেজ" else "Voice History",color=Color.White,fontWeight=FontWeight.Bold,fontSize=18.sp)};items(vm.history,key={it.id}){m->HistoryRow(m,vm)}};item{TextButton({vm.clear()}){Text(if(vm.bangla)"সব ইতিহাস মুছুন" else "Clear history",color=Rose)}}};item{Text(if(vm.bangla)"২৪,০০০ Hz স্টুডিও অডিও • Bengali & Hindi • Male & Female" else "24,000 Hz Studio Hi-Fi • Bengali & Hindi • Male & Female",color=Slate,fontSize=11.sp)}};if(icon)IconDialog(vm.bangla){icon=false};if(showSpoken){AlertDialog(onDismissRequest={showSpoken=false},confirmButton={TextButton({showSpoken=false}){Text("OK")}},title={Text(if(vm.bangla)"পাঠ্য" else "Spoken text")},text={Text(vm.current?.spoken.orEmpty())})}}

@Composable fun Header(vm:MainViewModel,onIcon:()->Unit){Row(verticalAlignment=Alignment.CenterVertically,modifier=Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Row(verticalAlignment=Alignment.CenterVertically){Surface(shape=RoundedCornerShape(12.dp),modifier=Modifier.size(46.dp),color=Color.Transparent){Text("DV",modifier=Modifier.fillMaxSize().background(Emerald).wrapContentSize(),color=Color(0xFF022C22),fontWeight=FontWeight.Black)};Spacer(Modifier.width(10.dp));Column{Text("Darks Voices AI",color=Color.White,fontWeight=FontWeight.Bold,fontSize=18.sp);Text(if(vm.bangla)"বাংলা ও হিন্দি • পুরুষ ও নারী কণ্ঠ" else "Bengali & Hindi • Male & Female",color=Slate,fontSize=10.sp)}};Row{TextButton(onIcon){Text(if(vm.bangla)"আইকন" else "Icon",color=Emerald)};TextButton({vm.bangla=!vm.bangla}){Text(if(vm.bangla)"EN" else "বাংলা",color=Slate)}}}}
@Composable fun Banner(vm:MainViewModel){Card(shape=RoundedCornerShape(16.dp),border=BorderStroke(1.dp,Emerald.copy(.35f))){Column(Modifier.padding(16.dp)){Text(if(vm.bangla)"বাংলা ও হিন্দি স্বাভাবিক কণ্ঠ (পুরুষ ও নারী)" else "Authentic Natural Voice Engine",color=Color.White,fontWeight=FontWeight.Bold);Spacer(Modifier.height(6.dp));Text(if(vm.bangla)"বাংলায় বা বাংলিশে যেকোনো টেক্সট লিখুন। সঠিক উচ্চারণ, স্বাভাবিক বিরতি এবং পুরুষ বা নারী কণ্ঠে বাস্তবসম্মত ভয়েস তৈরি করুন।" else "Type in native script or transliteration. Generate natural pauses, precise phonetics and authentic male or female voices.",color=Slate,fontSize=12.sp)}}}
@Composable fun Editor(vm:MainViewModel){Card(shape=RoundedCornerShape(16.dp)){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Row(verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.SpaceBetween,modifier=Modifier.fillMaxWidth()){Text(if(vm.lang=="hi")"हिन्दी टेक्स्ट या संदेश लिखें:" else if(vm.bangla)"বাংলা টেক্সট বা বার্তা লিখুন:" else "Enter Text or Message:",color=Color.White,fontWeight=FontWeight.SemiBold);Row{TextButton({vm.langChange("bn")}){Text("বাংলা",color=if(vm.lang=="bn")Emerald else Slate)};TextButton({vm.langChange("hi")}){Text("हिन्दी",color=if(vm.lang=="hi")Emerald else Slate)}}};val presets=if(vm.lang=="bn")bnPresets else hiPresets;Row(Modifier.horizontalScroll(rememberScrollState())){presets.forEach{(name,t)->AssistChip(onClick={vm.text=t},label={Text(name,fontSize=11.sp)});Spacer(Modifier.width(6.dp))}};val clip=LocalClipboardManager.current;OutlinedTextField(value=vm.text,onValueChange={vm.text=it},modifier=Modifier.fillMaxWidth().heightIn(min=150.dp),minLines=4,label={Text(if(vm.lang=="hi")"Text" else "টেক্সট")},supportingText={Text("${vm.text.trim().split(Regex("\\s+")).let{if(vm.text.isBlank())0 else it.size}} ${if(vm.lang=="hi")"शब्द" else "শব্দ"} • ${vm.text.length} ${if(vm.lang=="hi")"वर्ण" else "অক্ষর"}")});Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.End){TextButton({clip.setText(AnnotatedString(vm.text))}){Text(if(vm.bangla)"কপি" else "Copy")};TextButton({vm.text=""}){Text(if(vm.bangla)"মুছুন" else "Clear",color=Rose)};Button({vm.optimize()},enabled=vm.text.isNotBlank()&&!vm.optimizing){Text(if(vm.optimizing)"Optimizing..." else if(vm.bangla)"✨ উচ্চারণ ও বানান শুদ্ধ করুন" else "✨ Optimize")}}}}
@Composable fun VoiceSettings(vm:MainViewModel){Card(shape=RoundedCornerShape(16.dp)){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text(if(vm.bangla)"কণ্ঠ ও লিঙ্গ নির্বাচন করুন" else "Select Voice & Gender",color=Color.White,fontWeight=FontWeight.Bold);Row(Modifier.fillMaxWidth()){FilterChip(selected=vm.gender=="male",onClick={vm.selectGender("male")},label={Text(if(vm.bangla)"♂ পুরুষ" else "♂ Male")});Spacer(Modifier.width(8.dp));FilterChip(selected=vm.gender=="female",onClick={vm.selectGender("female")},label={Text(if(vm.bangla)"♀ নারী" else "♀ Female")})};val vs=if(vm.gender=="male")males else females;vs.forEach{v->Card(modifier=Modifier.fillMaxWidth().clickable{vm.selectVoice(v.id)},colors=CardDefaults.cardColors(containerColor=if(vm.voice==v.id)Emerald.copy(.16f) else Card),border=if(vm.voice==v.id)BorderStroke(1.dp,Emerald) else null){Column(Modifier.padding(12.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("${v.id} (${if(vm.lang=="bn")v.bn else v.hi})",color=Color.White,fontWeight=FontWeight.Bold);Text(if(vm.lang=="bn")v.badgeBn else v.badgeHi,color=Emerald,fontSize=10.sp)};Text(if(vm.lang=="bn")v.titleBn else v.titleHi,color=Emerald,fontSize=12.sp);Text(if(vm.lang=="bn")v.descBn else v.descHi,color=Slate,fontSize=11.sp)}}};Text(if(vm.bangla)"ডেলিভারি টোন" else "Delivery Tone",color=Color.White,fontWeight=FontWeight.SemiBold);Row(Modifier.horizontalScroll(rememberScrollState())){tones.forEach{t->FilterChip(selected=vm.tone==t.id,onClick={vm.tone=t.id},label={Text(if(vm.lang=="bn")t.bn else t.hi,fontSize=11.sp)});Spacer(Modifier.width(6.dp))}};Row(verticalAlignment=Alignment.CenterVertically){Switch(checked=vm.auto,onCheckedChange={vm.auto=it});Spacer(Modifier.width(8.dp));Text(if(vm.bangla)"স্বয়ংক্রিয় সঠিক উচ্চারণ ও যতিচিহ্ন অপ্টিমাইজেশন (অনুরোধিত)" else "Auto-optimize pronunciation & breath pauses (Recommended)",color=Slate,fontSize=11.sp)}}}

@Composable fun ErrorCard(e:String,onClose:()->Unit){Card(colors=CardDefaults.cardColors(containerColor=Rose.copy(.12f)),border=BorderStroke(1.dp,Rose.copy(.45f))){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){Text(e,color=Color(0xFFFFCDD2),modifier=Modifier.weight(1f),fontSize=12.sp);TextButton(onClose){Text("×",color=Rose,fontSize=20.sp)}}}}
@Composable fun Player(m:Msg,bn:Boolean,spoken:()->Unit){var playing by remember{mutableStateOf(false)};var progress by remember{mutableStateOf(0f)};var mp by remember{mutableStateOf<MediaPlayer?>(null)};val ctx=androidx.compose.ui.platform.LocalContext.current;DisposableEffect(m.id){onDispose{mp?.release()}};LaunchedEffect(playing){while(playing){val p=mp; if(p!=null&&p.duration>0) progress=(p.currentPosition.toFloat()/p.duration); kotlinx.coroutines.delay(150)}};Card(shape=RoundedCornerShape(16.dp),border=BorderStroke(1.dp,Emerald.copy(.4f))){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){Text(if(bn)"সক্রিয় ভয়েস মেসেজ" else "Active Voice Message",color=Color.White,fontWeight=FontWeight.Bold);Text(m.text,color=Slate,fontSize=12.sp);LinearProgressIndicator({progress},Modifier.fillMaxWidth());Row(verticalAlignment=Alignment.CenterVertically){Button({try{if(playing){mp?.pause();playing=false}else{val p=MediaPlayer();p.setDataSource(m.audioUrl);p.setOnPreparedListener{it.start();playing=true};p.setOnCompletionListener{playing=false;progress=0f};p.prepareAsync();mp=p}}catch(_:Exception){}}){Text(if(playing)"⏸" else "▶")};Spacer(Modifier.width(6.dp));TextButton(spoken){Text(if(bn)"পাঠ্য" else "Text")};TextButton({shareFile(ctx,m.audioUrl,"audio/wav")}){Text(if(bn)"শেয়ার" else "Share")};TextButton({saveToDownloads(ctx,m.audioUrl,"bengali_voice_${m.voice}_${SimpleDateFormat("yyyy-MM-dd_HH-mm",Locale.US).format(Date(m.timestamp))}.wav","audio/wav")}){Text("WAV")};TextButton({if(m.mp3Url!=null)saveToDownloads(ctx,m.mp3Url,"bengali_voice_${m.voice}_${SimpleDateFormat("yyyy-MM-dd_HH-mm",Locale.US).format(Date(m.timestamp))}.mp3","audio/mpeg")}){Text("MP3")}};Text("${m.voice} • ${(m.duration).format1()}s • ${m.sampleRate} Hz",color=Slate,fontSize=10.sp)}}}}

fun saveToDownloads(ctx:Context,path:String,name:String,mime:String){val resolver=ctx.contentResolver;val cv=android.content.ContentValues().apply{put(android.provider.MediaStore.Downloads.DISPLAY_NAME,name);put(android.provider.MediaStore.Downloads.MIME_TYPE,mime);put(android.provider.MediaStore.Downloads.IS_PENDING,1)};val uri=resolver.insert(android.provider.MediaStore.Downloads.EXTERNAL_CONTENT_URI,cv)?:return;resolver.openOutputStream(uri)?.use{out->File(path).inputStream().use{it.copyTo(out)}};cv.clear();cv.put(android.provider.MediaStore.Downloads.IS_PENDING,0);resolver.update(uri,cv,null,null)}
fun shareFile(ctx:Context,path:String,mime:String){val uri=androidx.core.content.FileProvider.getUriForFile(ctx,ctx.packageName+".fileprovider",File(path));ctx.startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).apply{type=mime;putExtra(Intent.EXTRA_STREAM,uri);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)},"Share audio"))}

@Composable fun HistoryRow(m:Msg,vm:MainViewModel){Card{Column(Modifier.padding(12.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text("${m.voice} • ${m.gender}",color=Emerald,fontWeight=FontWeight.Bold,fontSize=12.sp);Text(SimpleDateFormat("dd MMM, HH:mm",Locale.getDefault()).format(Date(m.timestamp)),color=Slate,fontSize=10.sp)};Text(m.text,color=Color.White,maxLines=2,fontSize=12.sp);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.End){TextButton({vm.current=m}){Text(if(vm.bangla)"চালু করুন" else "Open")};TextButton({vm.delete(m.id)}){Text(if(vm.bangla)"মুছুন" else "Delete",color=Rose)}}}}}
@Composable fun IconDialog(bn:Boolean,onClose:()->Unit){AlertDialog(onDismissRequest=onClose,confirmButton={TextButton(onClose){Text("OK")}},title={Text(if(bn)"অফিসিয়াল অ্যাপ আইকন" else "Official App Icon")},text={Column(horizontalAlignment=Alignment.CenterHorizontally){Text("Darks Voices AI • HD 512px",color=Slate);Spacer(Modifier.height(12.dp));Text("Native Android app icon is included with the APK.",fontSize=12.sp)}})}
private fun Double.format1()="%.1f".format(Locale.US)
